print(8)
print(8*2)
print(8**2)
print(8/2)
print(8//2)
print(8/0)

print("**********")
print(" ********")
print("  ******")
print("  ****")
print("   **")
print("   **")
print("  ****")
print("  ******")
print(" ********")
print("**********")

name = input('what is your name? ')
age = input('what is your age? ')
major = input('what is your major? ')
uni = input('what is your university? ')
print(f"My name is: {name}, my age is: {age}, majored in: {major}, and studying at: {uni}" )